apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: csharp-weather
  namespace: workloads
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: csharp-weather
spec:
  params:
    - name: gitops_server_address
      value: https://github.com/
    - name: gitops_repository_owner
      value: ajitkadari
    - name: gitops_repository_name
      value: tap-gitops
    - name: gitops_ssh_secret
      value: git-secret
    - name: gitops_commit_branch
      value: test
    - name: annotations
      value:
        autoscaling.knative.dev/minScale: "1"
  source:
    git:
      url: https://github.com/ajitkadari/csharp-weatherforecast.git
      ref:
        branch: main