apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: csharp-weather
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: csharp-weather
spec:
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "2"
  source:
    git:
      url: https://github.com/ajitkadari/csharp-weatherforecast
      ref:
        branch: main
